src/egenie/egenie/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from egenie.views import RootView, InfoView, ChoiceView, ApproveView, SetupView, RegisterView
from egenie.forms import SimpleLoginForm, UserCreateForm
from egenie.decorators import agree_required
from django.contrib.admin.views.decorators import staff_member_required
import spirit.urls
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^$', RootView.as_view(), name='root'),
    url(r'^info$', InfoView.as_view(), name='info'),
    url(r'^approve$', ApproveView.as_view(), name='approve'),
    url(r'^choice$', agree_required(ChoiceView.as_view()), name='choice'),
    url(r'^setup$', staff_member_required(SetupView.as_view()), name='setup'),

]


urlpatterns.extend([
    # Carousel Views
    url(r'^temperature/', include('temperature.urls'), name='temperature'),
    url(r'^alwayson/', include('alwayson.urls'), name='alwayson'),
    url(r'^graphs/', include('graphs.urls'), name='graphs'),

    # Inner Views
    url(r'^study/', include('psychology.urls',
                            namespace='psychology'), name='psychology'),
    url(r'^fm/', include('fm.urls')),
    url(r'^pinboard/', include('pinboard.urls', namespace='pinboard')),

    # Support Applications
    url(r'^sd_store/', include('sd_store.urls')),
    url(r'^annotation/', include('annotations.urls', namespace='annotations')),
    url(r'^spirit/', include(spirit.urls), name='spirit'),
    url(r'^sensors/', include('sensors.urls', namespace='sensors')),
    url(r'^deployments/', include('deployments.urls', namespace='deployments')),
])

urlpatterns.extend([
    # Login and Admin
    url(r'^accounts/login/$', login,
        {'authentication_form': SimpleLoginForm}, name='login'),
    url(r'^accounts/logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^accounts/register/$',
        RegisterView.as_view(form_class=UserCreateForm), name='register'),
    url(r'^admin/', include(admin.site.urls)),
])

src/egenie/fm/urls.py
from django.conf.urls import url
from fm import views
from django.views.generic import TemplateView

# from ctech.views import agree_required
from django.contrib.auth.decorators import login_required

app_name = 'fm'
urlpatterns = [
    url(r'^$', views.SendMessageView.as_view(), name='message'),
    url(r'^success$', TemplateView.as_view(
        template_name='fm/success.html'), name='success'),
]

src/egenie/pinboard/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from egenie.decorators import agree_required
from pinboard import views

app_name = 'pinboard'
urlpatterns = [
    url(r'^$', agree_required(views.PinboardView.as_view(
        category="user-posts")), name='public'),
    url(r'^private/$', login_required(agree_required(
        views.PinboardView.as_view(category="fm-messages"))), name='private'),
    url(r'^digest/$', views.DigestView.as_view(), name='digest'),
    url(r'^photo/delete/(?P<id>\d+)$',
        views.delete_photo, name='delete_photo'),
    url(r'^post$', views.post, name='post'),

    # Spirit overrides
    url(r'^topic/publish/$', views.topic_publish,
        name='topic_publish'),
    url(r'^topic/publish/(?P<category_id>\d+)/$',
        views.topic_publish, name='topic_publish'),
    url(r'^comment/(?P<topic_id>\d+)/publish/$',
        views.comment_publish, name='comment_publish'),
    url(r'^comment/(?P<topic_id>\d+)/publish/(?P<pk>\d+)/quote/$',
        views.comment_publish, name='comment_publish'),
    url(r'^comment/(?P<pk>\d+)/delete/$',
        views.comment_delete, name='comment_delete'),
]

src/egenie/psychology/urls.py
from django.conf.urls import url
from psychology import views
from egenie.decorators import agree_required
from django.contrib.auth.decorators import login_required

urlpatterns = [url(r'^goal$', views.GoalView.as_view(), name='goal'),
               url(r'^implementation/(?P<step>\d+)$',
                   views.ImplementationView.as_view(), name='implementation'),
               url(r'^wizard$', views.WizardView.as_view(), name='wizard'),
               url(r'^print$', views.PrintView.as_view(),
                   name='print_pledge'),
               url(r'^pledges/(?P<printer>[A-Z]+)$',
                   views.pledges, name='pledges'),
               ]

src/egenie/egenie/models.py
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.db import models
from deployments.models import Deployment
from sd_store.models import Sensor


class Participant(models.Model):
    """ When a User is created, a Participant model is also created. It only has two properties - the user, and whether they have agreed to participate in the study."""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    agreed = models.BooleanField(default=False)

    def __unicode__(self):
        return self.user.username + " (" + str(self.agreed) + ")"


def create_participant(sender, **kw):
    """ Create a Participant model when a User is created. """
    user = kw['instance']
    if kw['created']:
        participant = Participant(user=user, agreed=False)
        participant.save()


class Plinth(models.Model):
    """ A Plinth represents a physical podium within the deployment location, which displays the eGenie interface on a tablet. """

    location = models.CharField(max_length=32)
    """ Where this tablet is (e.g. Reception, Office). """

    printer = models.CharField(max_length=5)
    """ The unique code for the printer associated with this Plinth. """

    pi_ip = models.GenericIPAddressField()
    """ The psychology implementation can show a video feed of the user. This IP address points to the video stream. """

    deployment = models.ForeignKey(Deployment, blank=True, null=True)
    """ The Deployment associated with this Plint. """

    x = models.IntegerField()
    """ The x co-ordinate of the Plinth on the floorplan in pixels. """
    y = models.IntegerField()
    """ The y co-ordinate of the Plinth on the floorplan in pixels. """

    def __unicode__(self):
        return self.location


class SensorPosition(models.Model):
    """ Specifies where a Sensor is positioned on the Deployment's floor plan. """
    sensor = models.OneToOneField(Sensor, related_name='position')
    """ The Sensor this position refers to. """
    x = models.IntegerField()
    """ The x pixel coordinate of the Sensor on the floor plan. """
    y = models.IntegerField()
    """ The y pixel coordinate of the Sensor on the floor plan. """

    def __unicode__(self):
        return self.sensor.name + " (" + str(self.x) + "," + str(self.y) + ")"

post_save.connect(create_participant, sender=User,
                  dispatch_uid="users-participantcreation-signal")

src/egenie/egenie/forms.py
# This file is part of e-genie
#
# e-genie is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# e-genie is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with e-genie.  If not, see <http://www.gnu.org/licenses/>.


from django import forms
from django.contrib.auth import (
    authenticate, get_user_model,
)
from django.contrib.auth.models import User
from django.utils.translation import ugettext, ugettext_lazy as _
from django.utils.text import capfirst
from django.contrib.auth.forms import UserCreationForm

class UniqueUserEmailField(forms.EmailField):
    """
    An EmailField which is only valid if no other User has that email.
    """
    def validate(self, value):
        super(forms.EmailField, self).validate(value)
        try:
            User.objects.get(email = value)
            raise forms.ValidationError("Email already exists", code="exists")
        except User.MultipleObjectsReturned:
            raise forms.ValidationError("Email already exists", code="exists")
        except User.DoesNotExist:
            pass

class UserCreateForm(UserCreationForm):
    """ A user creation form that does not require a password, and requires a unique username."""
    email = UniqueUserEmailField(required=True)

    class Meta:
        model = User
        fields = ("email",)

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['password1'].required = False
        self.fields['password2'].required = False
        self.fields['password1'].widget.attrs['autocomplete'] = 'off'
        self.fields['password2'].widget.attrs['autocomplete'] = 'off'


    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.password = 'hello'
        if commit:
            user.save()
        return user

class SimpleLoginForm(forms.Form):
    """ A simplified login form. This only differs from the django.contrib.auth AuthenticationForm in that a password is not required for authentication. """

    username = forms.CharField(
        max_length=254, 
        widget=forms.TextInput(attrs={'autofocus':''}),
    )

    error_messages = {
        'invalid_login': _("Please enter a correct %(username)s and password. "
                           "Note that both fields may be case-sensitive."),
        'inactive': _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super(SimpleLoginForm, self).__init__(*args, **kwargs)

        # Set the label for the "username" field.
        UserModel = get_user_model()
        self.username_field = UserModel._meta.get_field(UserModel.USERNAME_FIELD)
        if self.fields['username'].label is None:
            self.fields['username'].label = capfirst(self.username_field.verbose_name)

    def clean(self):
        username = self.cleaned_data.get('username')

        if username:
            self.user_cache = authenticate(username=username)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': self.username_field.verbose_name},
                )
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        """
        Controls whether the given User may log in. This is a policy setting,
        independent of end-user authentication. This default behavior is to
        allow login by active users, and reject login by inactive users.
        If the given user cannot log in, this method should raise a
        ``forms.ValidationError``.
        If the given user may log in, this method should return None.
        """
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache

src/egenie/egenie/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, RedirectView, View
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse
from egenie.mixins import RestrictedMixin, PlinthMixin, AjaxableResponseMixin
from django.contrib.auth import logout
from egenie.models import Participant, Plinth
from django.contrib.auth.models import User
from django.core.mail import EmailMultiAlternatives
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse

from django.template.loader import get_template
from django.template import Context
from django.conf import settings
import datetime


class RootView(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('temperature')


class InfoView(TemplateView):
    template_name = 'egenie/info.html'

    def get_context_data(self, **kwargs):
        context = super(InfoView, self).get_context_data(**kwargs)
        context['next'] = self.request.GET.get('next')
        return context


class ChoiceView(TemplateView):
    template_name = 'egenie/choice.html'

    def get_context_data(self, **kwargs):
        context = super(ChoiceView, self).get_context_data(**kwargs)
        context['mode'] = self.request.GET.get('mode', 'heating')
        return context


class RegisterView(AjaxableResponseMixin, CreateView):
    model = User
    # fields = ['email']

    def make_unique_username(self, username):
        if not User.objects.filter(username=username).exists():
            return username

        for x in range(1, 500):
            new_username = username + str(x)
            if not User.objects.filter(username=new_username).exists():
                return new_username

    def form_invalid(self, form):
        status = form.errors.as_data()['email'][0].code
        return JsonResponse({'status': status})

    def form_valid(self, form):
        obj = form.save(commit=False)
        email = form.cleaned_data['email']
        username = email.split("@")[0]
        obj.username = self.make_unique_username(username)
        obj.password = User.objects.make_random_password()
        obj.save()

        textmail = get_template('egenie/register_email.txt')
        htmlmail = get_template('egenie/register_email.html')
        d = {'username': obj.username}
        subject, from_email, to = 'Welcome to GENIE', 'mailer@e-genie.co.uk', email
        text_content = textmail.render(d)
        html_content = htmlmail.render(d)
        msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
        msg.attach_alternative(html_content, 'text/html')
        msg.send()

        return JsonResponse({'status': 'success'})


class SetupView(RestrictedMixin, PlinthMixin, TemplateView):
    template_name = 'egenie/setup.html'

    def post(self, request, *args, **kwargs):
        response = redirect('setup')

        if self.request.POST.get('btn-reset', False):
            response.delete_cookie(key='plinthid')
        elif self.request.POST.get('btn-update', False):
            plinthid = self.request.POST.get('plinthid', 0)
            if plinthid:
                response.set_cookie(key='plinthid', value=plinthid, expires=datetime.datetime.now(
                ) + datetime.timedelta(days=365))

        return response


class ApproveView(RedirectView):

    def get(self, request, *args, **kwargs):
        response = super(ApproveView, self).get(request, *args, **kwargs)

        participant = Participant.objects.get(user=request.user)
        participant.agreed = True
        participant.save()
        return response

    def get_redirect_url(self, *args, **kwargs):
        return self.request.GET.get('next')


class RotatingView(RestrictedMixin, PlinthMixin, TemplateView):
    """ Rotating View """



    def get(self, request, *args, **kwargs):

        # All rotating views use a logged out state
        logout(request)
        context = self.get_context_data(**kwargs)
        response = self.render_to_response(context)
        return response

    def get_context_data(self, **kwargs):
        context = super(RotatingView, self).get_context_data(**kwargs)

        if context['onsite']:
            SCREEN_ORDER = settings.ONSITE_SCREEN_ORDER
        else:
            SCREEN_ORDER = settings.OFFSITE_SCREEN_ORDER

        if context['screen'] in SCREEN_ORDER:
            i = SCREEN_ORDER.index(context['screen'])
            prev_pos = i - 1
            next_pos = i + 1
            if prev_pos < 0:
                prev_pos = len(SCREEN_ORDER) - 1
            if next_pos > len(SCREEN_ORDER) - 1:
                next_pos = 0
        else:
            next_pos = 0
            prev_pos = 0
        context['next_screen'] = SCREEN_ORDER[next_pos]
        context['prev_screen'] = SCREEN_ORDER[prev_pos]
        return context

src/egenie/egenie/templates/egenie/choice.html
{% extends "base.html" %}

{% block styles %}{% endblock %}

{% block extra %}
{% endblock %}

{% block content %}

<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-default">
			<div class="panel-body">
				<h3 class="text-center">Now you've found an issue with the workplace, would you like to...</h3>
				<div class="row">
				<div class="col-md-12 choice-options text-center">
					<div><a class="btn btn-lg btn-primary" href="{% url 'psychology:wizard' %}?mode={{mode}}">Make A Pledge To Change?</a></div>
					<div><a class="btn btn-lg btn-primary" href="{% url 'pinboard:public' %}?mode={{mode}}">Start A Conversation?</a></div>
				</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

src/egenie/egenie/templates/egenie/floorplan.html
        <!-- Floor plan widget here -->
        <div id='floorplan'>
        </div>

        <script type="text/javascript">
        var w = 4230,
            h = 3635;

        var pixelToLatLng = function(x, y) {
            return map.unproject([x,y],map.getMaxZoom());
        };

        var show_markers = {{markers}};
        var show_plinth = {{at_plinth|lower}};


        var map = L.map('floorplan', {
          minZoom: 14,
          maxZoom: 18,
          zoom: 15,
          crs: L.CRS.Simple,
          zoomControl: true,
        });
        map.zoomControl.setPosition('topright');

        var southWest = map.unproject([0, h], map.getMaxZoom());
        var northEast = map.unproject([w, 0], map.getMaxZoom());
        map.setMaxBounds(new L.LatLngBounds(southWest, northEast));
        var tiles = L.tileLayer('/static/egenie/imgs/{{tiles_folder}}/{z}/map_{x}_{y}.png', {
            attribution: '',
        });
        map.addLayer(tiles);
        map.setView(pixelToLatLng(0,0),15);


        var plinthMarker = L.icon({
            iconUrl: '/static/egenie/imgs/plinth_marker.png',
            iconSize: [32,28],
        });

        var redMarker = L.AwesomeMarkers.icon({
            icon:'tachometer',
            markerColor:'red',
            prefix:'fa',
        });

        var greenMarker = L.AwesomeMarkers.icon({
            icon:'tachometer',
            markerColor:'green',
            prefix:'fa',
        });

        if(show_markers) {
            var temperature_sensors = [
            {% for sensor in all_sensors %}
            { 'id':{{sensor.id}}, 'x':{{sensor.position.x}}, 'y':{{sensor.position.y}} },
            {% endfor %}
            ];


            var marker_by_id = {};
            var all_markers = [];
            var is_selected = false;
            $.each(temperature_sensors, function(index, sensor) {
                var marker = L.marker(pixelToLatLng(sensor.x, sensor.y), {icon: redMarker}).addTo(map);
                all_markers.push(marker);
                marker_by_id[sensor.id] = marker;
                marker.on('click', function() {
                    resetTimer();
                    marker.setIcon(greenMarker);
                    // marker.setIcon(greenMarker);
                    $.each(all_markers, function(i, other_marker) {
                        if(marker !== other_marker) {
                            other_marker.setIcon(redMarker);
                        }
                    });
                    is_selected = true;
                    $("#floorplan").trigger('marker_clicked', {'marker':marker, 'data':sensor});
                });
            });
        }

        if(show_plinth) {
            var plinth_x = {{plinth.x}};
            var plinth_y = {{plinth.y}};
            var marker = L.marker(pixelToLatLng(plinth_x, plinth_y), {icon: plinthMarker}).addTo(map);
        }

        map.on('click', function() { resetTimer(); });


        // $.each(plinths, function(index, plinth) {
        //     var marker = L.marker(pixelToLatLng(plinth.x, plinth.y), {icon: plinthMarker}).addTo(map);
        // });
        // map.setView(all_markers[0].getLatLng(), 15);
        </script>
        <!-- End widget -->

src/egenie/egenie/templates/egenie/front_screen.html
{% extends "base.html" %}
{% load i18n static %}

{% block styles %}{% endblock %}

{% block scripts %}{% endblock %}

{% block nav %}
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="row">
        <div class="navbar-brand logo-bar">
          <a class="" href="{% url 'root' %}"><img class="logo" src="{% static 'egenie/imgs/lamp_logo.png' %}" /></a>
        </div>
        <ul class='nav navbar-nav'>
          <li><a href='/temperature'>Temperature</a></li>
          <!-- <li><a href='/alwayson'>Always On</a></li> -->
          <li><a href='/graphs'>Graphs</a></li>
          <li><a href='/pinboard'>Pinboard</a></li>
        </ul>
    </div>
</nav>
{% endblock %}
{% block content %}{% endblock %}

{% block extra %}

<div class="modal fade" id="aboutGenie" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">About e-Genie</h4>
      </div>
      <div class="modal-body">
        e-GENIE is a system developed by the CTech project. It shows how energy is used around the building, provides a place to discuss energy use and waste with your colleagues, and lets you make a pledge to reduce your own energy use.
        <hr />
        <div class="row valign">
          <div class="col-xs-3"><img src="{% static 'egenie/imgs/ctech.png' %}" width="100" /></div>
          <div class="col-xs-3"><img src="{% static 'egenie/imgs/notts.png' %}" width="100" /></div>
          <div class="col-xs-3"><img src="{% static 'egenie/imgs/soton.png' %}" width="100" /></div>
          <div class="col-xs-3"><img src="{% static 'egenie/imgs/cse.png' %}" width="100" /></div>
        </div>
        <hr />
      </div>
      <div class="modal-footer">
        <div class="row"><div class="col-xs-12 text-center">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div></div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="aboutScreen" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      {% block aboutscreen %}
      {% endblock aboutscreen %}
      <div class="modal-footer">
        <div class="row"><div class="col-xs-12 text-center">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div></div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
var current = '{{ screen }}';
var next_screen = '{% url next_screen %}';
var prev_screen = '{% url prev_screen %}';
</script>
<script src="{% static 'egenie/js/autorotate.js' %}"></script>
{% endblock %}



{% block footercont %}
{% if plinth %}
<footer class="footer navbar-fixed-bottom">
      <div class="container">
{% block footer %}
        <div class="col-sm-4">
            <div class="text-left"><button data-toggle="modal" data-target="#aboutGenie" class="btn btn-primary btn-lg">About e-Genie</button></div>
           </div>
        <div class="col-sm-4">
        {% comment %}{% if onsite %}{% endcomment %}
        <div class="text-center">
          <a href="{% url 'choice' %}?mode={{mode}}" class="btn btn-primary btn-lg">Think about changing your behaviour</a>
        </div>
        {% comment %}{% endif %}{% endcomment %}
        </div>
        <div class="col-sm-4">
            <div class="text-right"><button data-toggle="modal" data-target="#aboutScreen" class="btn btn-primary btn-lg">About This Screen</button></div>
        </div>
{% endblock %}
      </div>
</footer>
{% endif %}
{% endblock footercont %}

src/egenie/egenie/templates/egenie/info.html
{% extends "base.html" %}

{% block styles %}{% endblock %}

{% block extra %}
{% endblock %}
{% block title %}About GENIE{% endblock %}
{% block content %}

<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<div class="panel panel-default">
			<div class="panel-body">
				<p>GENIE is part of an academic research project.</p>
				<p>As part of this research your use of GENIE will be logged. This data will be anonymised prior to any publication.</p>
				<p>For further information, please see the email you were sent which contained your GENIE login. If you do not want to proceed, please use the Back button below.</p>
			</div>
		</div>
	</div>
</div>

{% endblock %}

{% block footercont %}
<footer class="footer">
    <div class="container">
		<a href="{% url 'root' %}" class="btn btn-primary btn-lg pull-left">Back</a>
		<a href="{% url 'approve' %}?next={{ next }}" class="btn btn-primary btn-lg pull-right">Continue</a>
	</div>
</footer>
{% endblock %}

src/egenie/egenie/templates/egenie/inner_screen.html
{% extends "base.html" %}
{% load i18n static %}

{% block extra %}
<script src="{% static 'egenie/js/timeout.js' %}"></script>
{% endblock %}

src/egenie/egenie/templates/egenie/register_email.html
Thank you for requesting a username for GENIE! As part of our C-TECH research project, we are trialling this software around the Digital Catapult. Your username is: <b>{{username}}</b>

<p>We are carrying out some research activities at the same time to understand how GENIE is being used we would like to invite you to take part in. All participation in the research is voluntary. If you do take part, you can chose to withdraw from the project at any time, and any recorded data associated with you will be deleted.</p>

<p>To evaluate GENIE, we (researchers from the University of Nottingham, Southampton University and the Centre for Sustainable Energy) are looking for staff and visitor volunteers for supporting study examining people’s attitudes and behaviours about energy use at work. 
The study involves completing a short (5-10 minute) online survey (<a href="https://horizon.qualtrics.com/SE/?SID=SV_6tWvSPGUdnEdBhX">click here</a>) and using the GENIE tool. We will also ask you to complete a further short (5-10 minute) online survey in a couple of weeks time. 
If you take part, you will receive £10 in Amazon vouchers as a thank you for your time. You will also gain insight into some of the active research going on in the project. 

<p>Below is some information on further research activities, and how we will manage any data on you that we do collect.</p>

<h2>The Data Collection</h2>
<p>In order to evaluate the trial, we will be collecting data through four different means:</p>
<p><b>GENIE usage:</b> what users click on when interacting with GENIE will be recorded by the system. The information displays presented by GENIE can be used anonymously, however the other elements of the system require users to log in. Once you are logged in, the route you take through GENIE will be visible to the research team in order to inform subsequent design work on GENIE. We may come back to you to ask if you would be willing to answer some questions about your use of the system. As with everything else, this is voluntary.</p>
<p><b>Observation and interview:</b> a C-TECH researcher will be spending some time in your office, in order to understand the organisation’s day-to-day workings, and gather feedback on GENIE as well as the wider energy-reduction programme. As well as observing interactions with GENIE, and asking questions about the experience of those using it where appropriate, we will also invite some of you to take part in interviews about energy use in the office. Before such interviews take place participants will be asked to sign a consent form allowing us to make an audio recording of it.</p>
<p><b>Video recording:</b> at certain points, video of users interacting with GENIE will be taken, if the user agrees to it. When the camera is recording, signs will notify those in the vicinity. Using GENIE at this time will be taken as consent for you to be filmed. Footage will be solely for internal use by the research team, unless we obtain signed permission from those present to use it publicly.</p>
<p><b>Survey:</b> As above, we'd appreciate your participation in a short online survey if you have not done so already - https://horizon.qualtrics.com/SE/?SID=SV_6tWvSPGUdnEdBhX</p>
<h2>What do I Need to Know?</h2>
<p>You are free to decline to participate at any point without giving a reason. All participation in the study is voluntary. Any personally-identifiable information you share with the research team – including decisions not to participate – will be strictly confidential and not shared with your employer or anyone else outside the research team, except with your explicit permission.</p>
<h2>How is Confidentiality Maintained?</h2>
<p>Real names will not be used in publications and reports. Research materials (‘raw data’) are confined to members of the research team, and any public presentation will use only data extracts that have been anonymized or, if this is not possible, with additional consent of those involved in that fragment. The researchers are independent and have no relation to your employer’s internal processes of accountability.</p>
<h2>What Happens to the Data Collected?</h2>
<p>All data will stored in accordance with the University of Nottingham’s Code of Research Conduct, namely on a password protected drive in a secure facility and only for the duration for which it is required. Any information you give us will be held securely and treated in strictest confidence.</p>
<h2>Who will Conduct the Research</h2>
<p>The observational research will be carried out by Dr Murray Goulden (murray.goulden@nottingham.ac.uk) and the survey research will be carried out by Dr Caroline Leygue (caroline.leygue@nottingham.ac.uk). The Principal Investigator of the project is Dr Alexa Spence (alexa.spence@nottingham.ac.uk).</p>

<h2>Contact for Further Information</h2>
<p>Dr Murray Goulden (observational research), Research Fellow: murray.goulden@nottingham.ac.uk</p>
<p>Dr Caroline Leygue (survey evaluation), Research Fellow: caroline.leygue@nottingham.ac.uk</p>
<p>Dr Alexa Spence (general enquiries), Lecturer: alexa.spence@nottingham.ac.uk</p>