src/egenie/egenie/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from egenie.views import RootView, InfoView, ChoiceView, ApproveView, SetupView, RegisterView
from egenie.forms import SimpleLoginForm, UserCreateForm
from egenie.decorators import agree_required
from django.contrib.admin.views.decorators import staff_member_required
import spirit.urls
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^$', RootView.as_view(), name='root'),
    url(r'^info$', InfoView.as_view(), name='info'),
    url(r'^approve$', ApproveView.as_view(), name='approve'),
    url(r'^choice$', agree_required(ChoiceView.as_view()), name='choice'),
    url(r'^setup$', staff_member_required(SetupView.as_view()), name='setup'),

]


urlpatterns.extend([
    # Carousel Views
    url(r'^temperature/', include('temperature.urls'), name='temperature'),
    url(r'^alwayson/', include('alwayson.urls'), name='alwayson'),
    url(r'^graphs/', include('graphs.urls'), name='graphs'),

    # Inner Views
    url(r'^study/', include('psychology.urls',
                            namespace='psychology'), name='psychology'),
    url(r'^fm/', include('fm.urls')),
    url(r'^pinboard/', include('pinboard.urls', namespace='pinboard')),

    # Support Applications
    url(r'^sd_store/', include('sd_store.urls')),
    url(r'^annotation/', include('annotations.urls', namespace='annotations')),
    url(r'^spirit/', include(spirit.urls), name='spirit'),
    url(r'^sensors/', include('sensors.urls', namespace='sensors')),
    url(r'^deployments/', include('deployments.urls', namespace='deployments')),
])

urlpatterns.extend([
    # Login and Admin
    url(r'^accounts/login/$', login,
        {'authentication_form': SimpleLoginForm}, name='login'),
    url(r'^accounts/logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^accounts/register/$',
        RegisterView.as_view(form_class=UserCreateForm), name='register'),
    url(r'^admin/', include(admin.site.urls)),
])

src/egenie/fm/urls.py
from django.conf.urls import url
from fm import views
from django.views.generic import TemplateView

# from ctech.views import agree_required
from django.contrib.auth.decorators import login_required

app_name = 'fm'
urlpatterns = [
    url(r'^$', views.SendMessageView.as_view(), name='message'),
    url(r'^success$', TemplateView.as_view(
        template_name='fm/success.html'), name='success'),
]

src/egenie/psychology/urls.py
from django.conf.urls import url
from psychology import views
from egenie.decorators import agree_required
from django.contrib.auth.decorators import login_required

urlpatterns = [url(r'^goal$', views.GoalView.as_view(), name='goal'),
               url(r'^implementation/(?P<step>\d+)$',
                   views.ImplementationView.as_view(), name='implementation'),
               url(r'^wizard$', views.WizardView.as_view(), name='wizard'),
               url(r'^print$', views.PrintView.as_view(),
                   name='print_pledge'),
               url(r'^pledges/(?P<printer>[A-Z]+)$',
                   views.pledges, name='pledges'),
               ]

src/egenie/psychology/models.py
from django.contrib.auth.models import User
from django.db import models


class PrintTask(models.Model):
    goal = models.CharField(max_length=16)
    printer = models.CharField(max_length=5)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)


class StepView(models.Model):
    stage = models.CharField(max_length=16)
    user = models.ForeignKey(User)
    goal = models.CharField(max_length=16, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.user.username + ", " + self.stage + ", " + self.goal

src/egenie/psychology/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from psychology.models import PrintTask
from psychology.models import StepView
import datetime
import time
import json

from egenie.mixins import PlinthMixin
from django.views.generic import TemplateView
from django.contrib.auth import get_user_model


class StudyView(PlinthMixin, TemplateView):
    """ Handles the running of a psychological intervention. """
    def get_context_data(self, **kwargs):
        """ Set up the context for this view. By default this uses the 
        anonymous user, and sets the initial goal to be heating, if not
        specified. """

        User = get_user_model()
        user = User.objects.get(username='anonymous')

        context = super(StudyView, self).get_context_data(**kwargs)
        context['mode'] = self.request.GET.get('mode', 'heating')
        stepview = StepView(user=user, stage=kwargs[
                            'stage'], goal=context['mode'])
        stepview.save()
        return context


class WizardView(StudyView):
    template_name = 'psychology/wizard.html'

    def get_context_data(self, **kwargs):
        context = super(WizardView, self).get_context_data(
            stage='wizard', **kwargs)
        return context


class GoalView(StudyView):
    template_name = 'psychology/goal.html'

    def get_context_data(self, **kwargs):
        context = super(GoalView, self).get_context_data(
            stage='goal', **kwargs)
        return context


class ImplementationView(StudyView):
    template_name = 'psychology/imp.html'

    def get_context_data(self, **kwargs):
        step = kwargs['step']

        if step == 4:
            tasks = PrintTask.objects.filter(user=self.request.user)

        context = super(ImplementationView, self).get_context_data(
            stage='imp' + str(step), **kwargs)
        return context

    def get_template_names(self):
        return ['psychology/imp%s.html' % self.kwargs['step']]


class PrintView(StudyView):

    template_name = 'psychology/printed.html'

    def get_context_data(self, **kwargs):

        User = get_user_model()
        user = User.objects.get(username='anonymous')

        context = super(PrintView, self).get_context_data(
            stage='print', **kwargs)
        printer = self.request.GET.get('printer', '')

        task = PrintTask(printer=printer, user=user, goal=context['mode'])
        task.save()

        return context

# def implementation(request, step):
# 	mode = request.GET.get('mode','heating')
# 	if step == 4:
# 		tasks = PrintTask.objects.filter(user=request.user)

# 	view = StepView(user=request.user, stage='imp'+str(step), goal=mode)
# 	view.save()

# 	return render(request, 'psychology/imp%s.html' % step, {'mode':mode})


def pledges(request, printer):
    tasks = PrintTask.objects.filter(printer=printer)
    out = []
    for task in tasks:
        out.append({'goal': task.goal, 'user': task.user.username})
        task.delete()
    return JsonResponse(out, safe=False)

# def print_pledge(request):
# 	mode = request.GET.get('mode', 'heating')
# 	printer = request.GET.get('printer', '')

# 	view = StepView(user=request.user, stage='print', goal=mode)
# 	view.save()

# 	task = PrintTask(printer=printer, user=request.user, goal=mode)
# 	task.save()
# 	return redirect('root')

src/egenie/psychology/templates/psychology/goal.html
{% extends "egenie/inner_screen.html" %}
{% load staticfiles %}

{% block styles %}
<link rel="stylesheet" href="{% static 'psychology/css/imp.css' %}">
{% endblock %}

{% block title %}Make A Pledge To Change{% endblock %}

{% block content %}

<div class="row">
	<div class="col-md-8 col-md-offset-2">
	<div class=" panel panel-default">
	<div class="panel-body">
		<div class="text-center">
		<img src="{% static 'psychology/imgs/cityscape.png' %}" />
		</div>
		<p class="text">Around 33% of greenhouse gas emissions in the UK are released from shared buildings within the business sector. So reducing energy use in the workplace has enormous potential in reducing climate change. Also, it helps your company save costs!</p>
		<p class="text">How about trying to reduce your energy use at work?</p>
		</div>
	</div>
	</div>
</div>
{% endblock %}

{% block footercont %}
<footer class="footer">
    <div class="container">
		<div class="text-center"><a href="{% url 'psychology:wizard' %}?mode={{ mode }}" class="btn btn-primary btn-lg">Next</a></div>
	</div>
</footer>
{% endblock %}

src/egenie/psychology/templates/psychology/imp1.html
{% extends "egenie/inner_screen.html" %}
{% load staticfiles %}

{% block styles %}
<link rel="stylesheet" href="{% static 'psychology/css/imp.css' %}">
{% endblock %}
{% block title %}Make A Pledge To Change{% endblock %}
{% block content %}

<div class="row">
	<div class="col-sm-12">
	<div class=" panel panel-default">
	<div class="panel-body">
	{% if mode == 'electricity' %}
		<p class="text">A simple method to help you reduce your own energy use is to plan how you will change your behaviour. This technique is found to help people remember to do something. For example, consider your actions if you see something that could be turned off. You could plan:</p>
		<h1 class="goal">"If I see something that can be turned off, then I will turn it off"</h1>
	{% elif mode == 'heating' %}
		<p class="text">A simple method to help you reduce your own energy use is to plan how you will change your behaviour. This technique is found to help people remember to do something. For example, consider your actions if you feel the temperature in the building is uncomfortable.  You could plan:</p>
		<h1 class="goal">"If I feel the temperature in the building is low, then I will put on another layer."</h1>
	{% endif %}
	</div>
	</div>
	</div>
</div>

{% endblock %}

{% block footercont %}
<footer class="footer">
    <div class="container">
		<div class="text-center"><a href="{% url 'psychology:implementation' step=2 %}?mode={{ mode }}" class="btn btn-primary btn-lg">Next</a></div>
	</div>
</footer>
{% endblock %}

src/egenie/psychology/templates/psychology/imp2.html
{% extends "egenie/inner_screen.html" %}
{% load staticfiles %}

{% block styles %}
<link rel="stylesheet" href="{% static 'psychology/css/imp.css' %}">
{% endblock %}
{% block title %}Make A Pledge To Change{% endblock %}
{% block content %}

<div class="row">
	<div class="col-sm-12">
	<div class=" panel panel-default">
	<div class="panel-body">
		<p class="text text-center">Now please create your own plans by tapping on the examples of cues and behaviours below</p>
		<div class="row vertical-align">
			<div class="col-sm-6 text-center"><h1 class="goal">If...</h1></div>
			<div class="col-sm-6 text-center"><h1 class="goal">Then...</h1></div>
		</div>
		<div class="row vertical-align">
			<div class="col-sm-6 text-center"><p class='text' onclick="$('p.text').css('background-color', 'white'); $(this).css('background-color', 'rgba(0, 0, 255, 0.2)'); $('#custom_if').text('the temperature is low'); $('#custom_then').text('...');">the temperature is low</p></div>
			<div class="col-sm-6 text-center"><p class='text pre_then' onclick="$('.pre_then').css('background-color', 'white'); $(this).css('background-color', 'rgba(0, 0, 255, 0.2)'); $('#custom_then').text('turn them off');">turn them off</p></div>
		</div>
		<div class="row vertical-align">
			<div class="col-sm-6 text-center"><p class='text' onclick="$('p.text').css('background-color', 'white'); $(this).css('background-color', 'rgba(0, 0, 255, 0.2)'); $('#custom_if').text('the temperature is uncomfortable'); $('#custom_then').text('...');">the temperature is uncomfortable</p></div>
			<div class="col-sm-6 text-center"><p class='text pre_then' onclick="$('.pre_then').css('background-color', 'white'); $(this).css('background-color', 'rgba(0, 0, 255, 0.2)'); $('#custom_then').text('turn off everything in my area');">turn off everything in my area</p></div>
		</div>
		<div class="row vertical-align">
			<div class="col-sm-6 text-center"><p class='text' onclick="$('p.text').css('background-color', 'white'); $(this).css('background-color', 'rgba(0, 0, 255, 0.2)'); $('#custom_if').text('I leave the office at the end of the day'); $('#custom_then').text('...');">I leave the office at the end of the day</p></div>
			<div class="col-sm-6 text-center"><p class='text pre_then' onclick="$('.pre_then').css('background-color', 'white'); $(this).css('background-color', 'rgba(0, 0, 255, 0.2)'); $('#custom_then').text('put on an extra layer');">put on an extra layer</p></div>
		</div>
		<div class="row vertical-align">
			<div class="col-sm-6 text-center"><p class='text' onclick="$('p.text').css('background-color', 'white'); $(this).css('background-color', 'rgba(0, 0, 255, 0.2)'); $('#custom_if').text('it is between 4pm and 7pm'); $('#custom_then').text('...');">it is between 4pm and 7pm</p></div>
			<div class="col-sm-6 text-center"><p class='text pre_then' onclick="$('.pre_then').css('background-color', 'white'); $(this).css('background-color', 'rgba(0, 0, 255, 0.2)'); $('#custom_then').text('reduce my electricity use');">reduce my electricity use</p></div>
		</div>
		<div class="row vertical-align">
			<div class="col-sm-6 text-center"><p class='text' onclick="$('p.text').css('background-color', 'white'); $(this).css('background-color', 'rgba(0, 0, 255, 0.2)'); $('#custom_if').text('I see things left on'); $('#custom_then').text('...');">I see things left on</p></div>
			<div class="col-sm-6 text-center"><p class='text pre_then' onclick="$('.pre_then').css('background-color', 'white'); $(this).css('background-color', 'rgba(0, 0, 255, 0.2)'); $('#custom_then').text('discuss moving desks with my colleagues');">discuss moving desks with my colleagues</p></div>
		</div>
		<div class='row vertical-align'>
			<div class='col-sm-12 text text-center'>
				<p><strong>If <span id="custom_if">...</span> then I will <span id="custom_then">...</span></strong></p>
				<p>Please try and remember your plan.</p>
			</div>
		</div>
	</div>
	</div>
	</div>
</div>

{% endblock %}

{% block footercont %}
<footer class="footer">
    <div class="container">
		<div class="text-center"><a href="{% url 'root' %}" class="btn btn-primary btn-lg">Well done!</a></div>
	</div>
</footer>
{% endblock %}

src/egenie/psychology/templates/psychology/imp3.html
{% extends "egenie/inner_screen.html" %}
{% load staticfiles %}

{% block styles %}
<link rel="stylesheet" href="{% static 'psychology/css/imp.css' %}?cache=false">
{% endblock %}
{% block title %}Make A Pledge To Change{% endblock %}
{% block content %}

<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<p class="text">Research also finds that reading specific actions helps you remember to do them. Please read the action from the speech bubble below:</p>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-3 text-center">
		<img src="http://{{plinth.pi_ip}}/"  class="video text-center"/>
		<p>Don't worry, we aren't recording!</p>
	</div>
	<div class="col-sm-7">
		<div class="bubble">
			{% if mode == 'electricity' %}
			If I see something that can be turned off, then I will turn it off
			{% elif mode == 'heating' %}
			If I feel the temperature in the building is uncomfortable, then I will make sure my local systems are working and report any faults or adjustments needed.
			{% endif %}
		</div>
	</div>
</div>

{% endblock %}

{% block footercont %}
<footer class="footer">
    <div class="container">
		<div class="text-center"><a href="{% url 'psychology:implementation' step=4 %}?mode={{ mode }}" class="btn btn-primary btn-lg next-button">Next</a></div>
	</div>
</footer>
{% endblock %}

{% block extra %}
{{ block.super }}
{% endblock %}

src/egenie/psychology/templates/psychology/imp4.html
{% extends "egenie/inner_screen.html" %}
{% load staticfiles %}

{% block styles %}
<link rel="stylesheet" href="{% static 'psychology/css/imp.css' %}">
{% endblock %}
{% block title %}Make A Pledge To Change{% endblock %}
{% block content %}

<div class="row">
	<div class="col-sm-12">
		<div class=" panel panel-default">
			<div class="panel-body">
				{% if mode == 'electricity' %}
				<h1 class="goal">If I see something that can be turned off, then I will turn it off.</h1>
				{% elif mode == 'heating' %}
				<h1 class="goal">If I feel the temperature in the building is uncomfortable, then I will make sure my local systems are working and report any faults or adjustments needed.</h1>
				{% endif %}
				<p class="text">Please now press “Print” to print this action as a further reminder and help yourself to a chocolate bar if you’d like one.</p>
				<div class="row">
				<div class="col-sm-6 text-center vcenter">
				<img src="{% static 'psychology/imgs/pipsta.png' %}" width="400" />
				</div><div class="col-sm-6 text-center vcenter">
				<img src="{% static 'psychology/imgs/chocolate.png' %}" width="300" />
				</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

{% block footercont %}
<footer class="footer">
    <div class="container">
		<div class="text-center"><a href="{% url 'psychology:print_pledge' %}?mode={{mode}}&printer={{plinth.printer}}" class="btn btn-primary btn-lg next-button">Print Pledge</a></div>
	</div>
</footer>
{% endblock %}

src/egenie/psychology/templates/psychology/printed.html
{% extends "egenie/inner_screen.html" %}
{% load staticfiles %}

{% block styles %}
<link rel="stylesheet" href="{% static 'psychology/css/imp.css' %}">
{% endblock %}
{% block title %}Make A Pledge To Change{% endblock %}
{% block content %}

<div class="row">
	<div class="col-sm-12">
		<div class=" panel panel-default">
			<div class="panel-body">
				{% if mode == 'electricity' %}
				<h1 class="goal">If I see something that can be turned off, then I will turn it off.</h1>
				{% elif mode == 'heating' %}
				<h1 class="goal">If I feel the temperature in the building is uncomfortable, then I will make sure my local systems are working and report any faults or adjustments needed.</h1>
				{% endif %}
			</div>
		</div>

	
	    <div class="alert-success alert">
	        <div class="row">
		        <div class="col-sm-6">Done! Your pledge will be printed shortly.</div>
			    <div class="col-sm-6 text-right"><a href="{% url 'root' %}" class="btn btn-primary">Back</a></div>
	        </div>
	    </div>
	</div>
</div>

{% endblock %}

{% block footercont %}
<footer class="footer">
    <div class="container">
		<div class="text-center"><a href="{% url 'choice' %}" class="btn btn-primary btn-lg next-button">Take Another Action</a></div>
	</div>
</footer>
{% endblock %}

src/egenie/psychology/templates/psychology/wizard.html
{% extends "egenie/inner_screen.html" %}
{% load staticfiles %}

{% block styles %}
<link rel="stylesheet" href="{% static 'psychology/css/imp.css' %}">
<link rel="stylesheet" href="{% static 'psychology/css/wizard.css' %}">
{% endblock %}
{% block title %}Make A Pledge To Change{% endblock %}
{% block content %}

<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<p class="text wizard-text">A large part of greenhouse gas emissions are released from non domestic buildings. Performed regularly, several behaviours can help reduce a lot of energy. For example:</p>

				<ul class="wizard-examples">
				<li class="row">
					<div class="col-sm-8 behaviour">Turn off everything in my area when I leave the office.</div>
					<div class="col-sm-4 text-right"><img src="{% static 'psychology/imgs/imac.png' %}" /></div>
				</li>
				<li class="row">
					<div class="col-sm-8 behaviour">Turn off devices when I see that they are not being used.</div>
					<div class="col-sm-4 text-right"><img src="{% static 'psychology/imgs/printer.png' %}" /></div>
				</li>
				<li class="row">
					<div class="col-sm-8 behaviour">Put on another layer when it's cold in the office, rather than ask for the temperature to be increased.</div>
					<div class="col-sm-4 text-right"><img src="{% static 'psychology/imgs/clothes.png' %}" /></div>
				</li>
				</ul>
			</div>
		</div>
	</div>
</div>

{% endblock %}

{% block footercont %}
<footer class="footer">
    <div class="container">
		<div class="text-center"><a href="{% url 'psychology:implementation' step=1 %}?mode={{ mode }}" class="btn btn-primary btn-lg">Next</a></div>
	</div>
</footer>
{% endblock %}