src/egenie/fm/urls.py
from django.conf.urls import url
from fm import views
from django.views.generic import TemplateView

# from ctech.views import agree_required
from django.contrib.auth.decorators import login_required

app_name = 'fm'
urlpatterns = [
    url(r'^$', views.SendMessageView.as_view(), name='message'),
    url(r'^success$', TemplateView.as_view(
        template_name='fm/success.html'), name='success'),
]

src/egenie/pinboard/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from egenie.decorators import agree_required
from pinboard import views

app_name = 'pinboard'
urlpatterns = [
    url(r'^$', agree_required(views.PinboardView.as_view(
        category="user-posts")), name='public'),
    url(r'^private/$', login_required(agree_required(
        views.PinboardView.as_view(category="fm-messages"))), name='private'),
    url(r'^digest/$', views.DigestView.as_view(), name='digest'),
    url(r'^photo/delete/(?P<id>\d+)$',
        views.delete_photo, name='delete_photo'),
    url(r'^post$', views.post, name='post'),

    # Spirit overrides
    url(r'^topic/publish/$', views.topic_publish,
        name='topic_publish'),
    url(r'^topic/publish/(?P<category_id>\d+)/$',
        views.topic_publish, name='topic_publish'),
    url(r'^comment/(?P<topic_id>\d+)/publish/$',
        views.comment_publish, name='comment_publish'),
    url(r'^comment/(?P<topic_id>\d+)/publish/(?P<pk>\d+)/quote/$',
        views.comment_publish, name='comment_publish'),
    url(r'^comment/(?P<pk>\d+)/delete/$',
        views.comment_delete, name='comment_delete'),
]

src/egenie/pinboard/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.contrib.auth.models import User

from spirit.comment.models import Comment

import random
import string


class PinboardPhoto(models.Model):
    image = models.ImageField(upload_to='uploads')
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.image.name


class CommentPhoto(models.Model):
    comment = models.ForeignKey(Comment, related_name='comment_photo')
    photo = models.ForeignKey(PinboardPhoto, related_name='photo_comment')


class CommentAuthor(models.Model):
    comment = models.ForeignKey(Comment, related_name='comment_author')
    author = models.CharField(max_length=50)


class UserPinboardProfile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    code = models.CharField(max_length=6)

    def __unicode__(self):
        return self.user.username


def create_pinboard_profile(sender, **kw):
    user = kw['instance']
    if kw['created']:
        code = ''.join(random.choice(string.ascii_uppercase +
                                     string.digits) for _ in range(5))
        profile = UserPinboardProfile(user=user, code=code)
        profile.save()

post_save.connect(create_pinboard_profile, sender=User,
                  dispatch_uid="users-pinboardprofile-signal")

src/egenie/pinboard/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.conf import settings
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect


from spirit.comment.forms import CommentForm
from spirit.comment.utils import comment_posted
from spirit.topic.forms import TopicForm
from spirit.core.utils import markdown, paginator, render_form_errors, json_response

from spirit.category.models import Category
from spirit.topic.models import Topic
from spirit.comment.models import Comment
from spirit.core.utils.paginator import yt_paginate

from egenie.decorators import agree_required
from egenie.views import RotatingView
from pinboard.models import PinboardPhoto, UserPinboardProfile, CommentPhoto, CommentAuthor

from django.contrib.auth import get_user_model


@login_required
@agree_required
def comment_delete(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    Comment.objects.filter(pk=pk, user=None).update(is_removed=True)

    remaining = Comment.objects.filter(topic=comment.topic, is_removed=False)
    if remaining.count() == 0:
        category = comment.topic.category
        if category.slug == settings.PUBLIC_CATEGORY:
            return redirect('pinboard:public')
        elif category.slug == settings.PRIVATE_CATEGORY:
            return redirect('pinboard:private')
    else:
        return redirect('spirit:topic:detail', pk=comment.topic.pk)


def comment_publish(request, topic_id, pk=None):
    topic = get_object_or_404(
        Topic.objects.opened(),
        pk=topic_id
    )

    if request.method == 'POST':
        User = get_user_model()
        user = User.objects.get(username='anonymous')
        form = CommentForm(user=user, topic=topic, data=request.POST)

        category = topic.category

        if form.is_valid():
            comment = form.save()
            comment.user = user
            comment.save()

            author = request.POST.get('author', False)

            if author:
                comment_author = CommentAuthor(comment=comment, author=author)
                comment_author.save()

            comment_posted(comment=comment, mentions=form.mentions)

            if category.slug == settings.PUBLIC_CATEGORY:
                return redirect('pinboard:public')
            elif category.slug == settings.PRIVATE_CATEGORY:
                return redirect('pinboard:private')
    else:
        initial = None

        if pk:
            comment = get_object_or_404(
                Comment.objects.for_access(user=None), pk=pk)
            quote = markdown.quotify(comment.comment, comment.user.username)
            initial = {'comment': quote, }

        form = CommentForm(initial=initial)

    context = {
        'form': form,
        'topic': topic,
    }

    return render(request, 'spirit/comment/publish.html', context)


def topic_publish(request, category_id=None):
    if category_id:
        get_object_or_404(Category.objects.visible(),
                          pk=category_id)

    if request.method == 'POST':

        # no longer using user auth so set user to anonymous
        # author name entered later from form
        User = get_user_model()
        user = User.objects.get(username='anonymous')

        form = TopicForm(user=user, data=request.POST)
        cform = CommentForm(user=user, data=request.POST)
        photo_id = request.POST.get('photo', 0)

        if all([form.is_valid(), cform.is_valid()]):  # TODO: test!

            # wrap in transaction.atomic?
            topic = form.save()
            topic.user = user
            topic.save()
            cform.topic = topic
            comment = cform.save()
            comment.user = user
            comment.save()
            if photo_id:
                photo = get_object_or_404(PinboardPhoto, pk=photo_id)
                comment_photo = CommentPhoto(comment=comment, photo=photo)
                comment_photo.save()

            author = request.POST.get('author', False)

            if author:
                comment_author = CommentAuthor(comment=comment, author=author)
                comment_author.save()

            comment_posted(comment=comment, mentions=cform.mentions)

            if topic.category.slug == settings.PUBLIC_CATEGORY:
                return redirect('pinboard:public')
            elif topic.category.slug == settings.PRIVATE_CATEGORY:
                return redirect('pinboard:private')
    else:
        if not category_id:
            slug = request.GET.get('category', settings.PUBLIC_CATEGORY)
            category_id = Category.objects.get(slug=slug).id
        form = TopicForm(user=None, initial={'category': category_id, })
        cform = CommentForm()

    context = {
        'form': form,
        'cform': cform,
        'category': category_id,
    }

    photo_id = request.GET.get('photo', 0)
    if photo_id:
        context['photo'] = get_object_or_404(PinboardPhoto, pk=photo_id)

    return render(request, 'spirit/topic/publish.html', context)


def get_filtered_posts(topics):
    filtered = []
    for topic in topics:
        comments = Comment.objects.filter(
            topic=topic, is_removed=False).order_by('date')
        if comments.count() > 0:
            author = comments[0].comment_author.first()
            if author:
                setattr(comments[0], 'author', author.author)
            filtered.append(comments[0])

    return filtered


def post(request):
    context = {}
    return render(request, 'pinboard/post.html', context)


def delete_photo(request, id):
    photo = get_object_or_404(UserPinboardPhoto, pk=id)
    photo.delete()
    return redirect('pinboard:public')


class PinboardView(TemplateView):
    """ PinboardView provides a simple forum where users can post
    comments, or reply to others. There are two categories - public
    and private (i.e. for everyone, or for just the facilities manager).
    This view renders the main forum display.
    """

    template_name = 'pinboard/index.html'
    category = settings.PUBLIC_CATEGORY

    @method_decorator(agree_required)
    def dispatch(self, *args, **kwargs):
        return super(PinboardView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(PinboardView, self).get_context_data(
            screen='pinboard:public', **kwargs)
        recent_topics = Topic.objects.filter(
            category__slug=self.category).order_by('-last_active')

        photos = PinboardPhoto.objects.order_by('-created')
        context['comments'] = get_filtered_posts(recent_topics)
        context['photos'] = photos

        #context['profile'] = UserPinboardProfile.objects.filter(user=self.request.user)[0]
        context['category'] = self.category
        return context


class DigestView(RotatingView):
    """ DigestView is one of the tablet carousel screens, which just shows a few of the
    most recent and most popular posts. """
    
    template_name = 'pinboard/digest.html'

    def get_context_data(self, **kwargs):
        context = super(DigestView, self).get_context_data(
            screen='pinboard:digest', **kwargs)

        # Base it on topics
        recent_topics = Topic.objects.filter(
            category__slug=settings.PUBLIC_CATEGORY).order_by('-last_active')[0:5]
        popular_topics = Topic.objects.filter(category__slug=settings.PUBLIC_CATEGORY).order_by(
            '-view_count', '-last_active')[0:5]
        fm_topics = Topic.objects.filter(
            category__slug=settings.PRIVATE_CATEGORY).order_by('-last_active')[0:5]

        context['recent'] = get_filtered_posts(recent_topics)
        context['popular'] = get_filtered_posts(popular_topics)
        context['mode'] = 'electricity'

        return context

src/egenie/pinboard/templates/spirit/topic/detail.html
{% extends "egenie/inner_screen.html" %}

{% load spirit_tags i18n static %}
{% load thumbnail %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'egenie/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'pinboard/css/pinboard.css' %}">
{% endblock %}

{% block extra %}
{{ block.super }}
{% endblock %}

{% block title %}Start A Conversation{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-6">
    {% for c in comments %}
    {% if not c.is_removed %}
        <div class="comment-panel-large panel panel-{% if forloop.counter == 1 %}primary {% else %}default{% endif %}">
            <div class="panel-heading">

                <div class="row">
                    <div class="col-sm-6 text-left">
                    {{ c.date }}
                    </div>
                    <div class="col-sm-6 text-right">
                        <div class="username"><i class="fa fa-user"></i>&nbsp;{{ c.comment_author.first.author }}</div>
                    </div>
                </div>
            </div>

            <div class="panel-body comment">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="comment-body">
                            <blockquote>
                            <p><a href="{% url 'spirit:topic:detail' pk=c.topic.id %}">{{ c.comment }}</a></p>
                            </blockquote>
                        </div>
                    </div>
                    {% if c.comment_photo.all.count > 0 %}
                    {% with c.comment_photo.all|first as first_photo %}
                    <div class="col-sm-3 comment-image">
                        {% thumbnail first_photo.photo.image "150x150" crop="center" as im %}
                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" />
                        {% endthumbnail %}
                    </div>
                    {% endwith %}
                    {% endif %}
                </div>
            </div>
            {% if c.user == request.user %}
            <div class="panel-footer">
                <a href="{% url 'pinboard:comment_delete' pk=c.id %}" class="btn btn-default">Delete</a> 
            </div>
            {% endif %}
        </div> 
    {% endif %}
    {% endfor %}
    </div>
</div>
<a name="add_post"></a>
<form action="{% url 'pinboard:comment_publish' topic.id %}" method="post">
{% csrf_token %}
    <div class="row">
    {% with comments|first as first_comment %}
    {% if first_comment.topic.category.slug == 'fm-messages' %}
    {% include "pinboard/_entry.html" with category=first_comment.topic.category.pk %}
    {% elif first_comment.topic.category.slug == 'user-posts' %}
    {% include "pinboard/_entry.html" with category=first_comment.topic.category.pk %}
    {% endif %}
    {% endwith %}
    </div>
</form>
{% endblock %}

src/egenie/pinboard/templates/spirit/topic/publish.html
{% extends "egenie/inner_screen.html" %}

{% load spirit_tags i18n static %}
{% load thumbnail %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'egenie/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'pinboard/css/pinboard.css' %}">
{% endblock %}

{% block extra %}
{{ block.super }}
{% endblock %}

{% block title %}Start A Conversation{% endblock %}
{% block content %}
<form action="." method="post">
{% csrf_token %}
    <div class="row">
        <input type="hidden" name="title" value="Untitled" />
        {% if mode == 'public' %}
        <input type="hidden" name="category" value="2" />
        {% elif mode == 'private' %}
        <input type="hidden" name="category" value="3" />
        {% endif %}


        {% include "pinboard/_entry.html" with mode=mode %}

        {% if photo %}
        <input type="hidden" name="photo" value="{{ photo.id }}" />        
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-body comment-image">
                    {% thumbnail photo.image "200x200" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"/>
                    {% endthumbnail %}
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</form>
{% endblock %}